### ISSUE TITLE
Unable to launch under MacOS Big Sur

### ISSUE THREAD

**Issue by igor1661** [florentbr/OWON-VDS1022#16] opened 2020-12-23 14:10 UTC
Hi --
Unable to start release 1.0.33-cf11 under MacOS Big Sur version 11.1.
The previous versions work fine.
Igor

**Comment by florentbr** [comment] 2020-12-23 19:30
This issue is due to a regression introduced by release 1.0.33-cf11. To make it work, remove `-XstartOnFirstThread\\` line 66 in `install-mac.sh`.

**Comment by igor1661** [comment] 2020-12-23 23:23
I've removed the line 66 from the install-mac.sh. 
Now it works as expected.
Thank you!

**Comment by florentbr** [comment] 2020-12-26 13:05
keeping this issue open until fixed

**Comment by florentbr** [comment] 2021-03-02 21:47
fixed in release 1.0.33-cf12

**Closed by florentbr** 2021-03-02 21:47 UTC
Labels: bug
