### ISSUE TITLE
Can not select options in  combo boxes

### ISSUE THREAD

**Issue by meibye** [florentbr/OWON-VDS1022#3] opened 2020-01-12 13:28 UTC
When I select the small triangle pointing downwards in a combo box such as Mode in the Trigger function, I get the foillowing options presented Edge, Video, Slope, Puls. However, when I try to move the cursoe down the combo box either just closes or it modifies the presented options to only Edge, Video. Hence, it is not possible to select e.g. Slope. The same holds for other combo boxes, e.g. Language in Utility, it starts by showing all languages then reduced the selection set to the top 2.

It does not seem to be the case with all combo boxes, but most of them.

**Comment by florentbr** [comment] 2020-01-12 13:49
I can't reproduce the issue on Windows 10 or Linux.  
Which version of Windows are you using  ?  
Which version of Java have you installed (`%JAVA_HOME%\bin\java.exe -version`) ?  
Can you provide a screenshot ?

**Comment by meibye** [comment] 2020-01-12 14:40
I am using Windows 10 Pro version 1909

The Java version is given by the information below.

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode)

Finally I have attached a small MP4 video in inside the zip showing the problem. I hope you can see it.
[OWON VDS1022 combo error_1.zip](https://github.com/florentbr/OWON-VDS1022/files/4050736/OWON.VDS1022.combo.error_1.zip)

**Comment by florentbr** [comment] 2020-01-13 17:08
Fixed in release 1.0.30-cf8

**Closed by florentbr** 2020-01-13 17:08 UTC

**Comment by meibye** [comment] 2020-01-14 15:41
It works. Thanks
